require:
  - rubocop-performance
  - rubocop-rails

inherit_from: .rubocop_todo.yml

AllCops:
  EnabledByDefault: true
Layout/EmptyLines:
  Exclude:
    - 'db/migrate/**'
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/**'
Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
Layout/LineLength:
  Max: 120
  Exclude:
    - 'db/migration/**'
    - 'db/schema.rb'
Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/schema.rb'
Style/NumericLiterals:
  Exclude:
    - db/schema.rb
Style/StringLiterals:
  Exclude:
    - db/schema.rb
