# Not really interested in rubocop offences for the db/migrate folder
Layout/EmptyLines:
  Exclude:
    - '*.rb'
Style/Documentation:
  Exclude:
    - '*.rb'
Style/FrozenStringLiteralComment:
  Exclude:
    - '*.rb'
Style/StringLiterals:
  Exclude:
    - '*.rb'
Metrics/LineLength:
  Exclude:
    - '*.rb'
Metrics/MethodLength:
  Exclude:
    - '*.rb'
